server {
	listen 8080;
	server_name www.example.com;
	error_page 400 /req_error.html;
	error_page 401 403 404 /error.html;
	index index.html;
	client_max_body_size 10000;
	root	/home;
	location / {
		allow_methods GET POST;
		root ./www;
		index index.html;
		autoindex on;
upload_store ./uploads;
	}
location /test_delete {
    allow_methods GET DELETE;
    root ./delete_test;
}
	location /src_path {
		root /home/mcuenca-/root;
		cgi .py /excev_path;
	}
	location /src_redirect {
		allow_methods GET DELETE;
		return 301 /web.html;
	}
}

server {
	listen 8081 default_server;
	server_name example.com;
	root /var/www/example;
	client_header_timeout 1ms;
	client_body_timeout 1ms;
	send_timeout 1ms;
	keepalive_timeout 1ms;
}
