server {
	listen 127.0.0.1:42;
	server_name www.example.com;
	error_page 400 /req_error.html;
	error_page 401 403 404 /error.html;
	client_max_body_size 10000;
	root	/home;
	location / {
		allow_methods GET DELETE;
		root /home/mcuenca-;
		index index.html;
		autoindex on;
		upload_store /home/mcuenca-/42/webserver/upload;
	}
	location /src_path {
		root /home/mcuenca-/root;
		cgi {
				.py /excev_path;
		}
	}
	location /src_redirect {
		return 305 /proxy.html;
	}
}

server {
	listen 80 default_server;
	server_name example.com;
	root /var/www/example;
}
