

server {
    listen 8080;
    root ./www;
    index index.html;
    location / {
        allow_methods GET;
        root ./www;
        index index.html;
        autoindex on;
        upload_store ./uploads;
    }
}

server {
    listen 127.3.0.1:8081;
    server_name localhost;

    root ./website2;
    index index.html;

    client_max_body_size 5M;

    error_page 404 ./website2/errors/404.html;

}

server {
    listen 8082 default_server;
    server_name example.com;
    root ./www;
    index web.html;
    client_header_timeout 10ms;
    client_body_timeout 10ms;
    send_timeout 10ms;
    keepalive_timeout 10ms;
    location / {
        allow_methods GET;
        autoindex on;
        upload_store ./uploads;
    }
}
