# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    config.conf                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mgrandia <mgrandia@student.42barcelona.co  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/07/01 13:12:01 by mgrandia          #+#    #+#              #
#    Updated: 2026/07/01 13:12:14 by mgrandia         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

server {
    listen 8080;
    root ./www;
    index index.html;
}
